// <auto-generated />
using System;
using Gruppe5.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gruppe5.Migrations
{
    [DbContext(typeof(Gruppe5Context))]
    [Migration("20240524012859_secondmigration")]
    partial class secondmigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Gruppe5.Models.Level", b =>
                {
                    b.Property<string>("LevelType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.ToTable("Level");
                });

            modelBuilder.Entity("Gruppe5.Models.Observation", b =>
                {
                    b.Property<Guid>("Elementid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("RootObjectSourceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TimeOffset")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TimeResolution")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TimeSeriesId")
                        .HasColumnType("int");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.HasKey("Elementid");

                    b.HasIndex("RootObjectSourceId");

                    b.ToTable("Observation");
                });

            modelBuilder.Entity("Gruppe5.Models.RootObject", b =>
                {
                    b.Property<Guid>("SourceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ReferenceTime")
                        .HasColumnType("datetime2");

                    b.HasKey("SourceId");

                    b.ToTable("RootObject");
                });

            modelBuilder.Entity("Gruppe5.Models.WeatherForecast", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<double>("Temperature")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("WeatherForecast");
                });

            modelBuilder.Entity("Gruppe5.Models.Observation", b =>
                {
                    b.HasOne("Gruppe5.Models.RootObject", null)
                        .WithMany("Observations")
                        .HasForeignKey("RootObjectSourceId");
                });

            modelBuilder.Entity("Gruppe5.Models.RootObject", b =>
                {
                    b.Navigation("Observations");
                });
#pragma warning restore 612, 618
        }
    }
}
